# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
    #  contentDir: content/en
  menus:
    main:
      - name: Research
        url: research
        weight: 10
      - name: People
        url: people
        weight: 20
      - name: News
        url: post
        weight: 30
      - name: Publications
        url: publication
        weight: 40
      - name: Contact
        url: contact
        weight: 50
es:
  languageCode: es
#  contentDir: content/es
  menus:
    main:
      - name: Investigación
        url: research
        weight: 10
      - name: Equipo
        url: people
        weight: 20
      - name: Noticias
        url: post
        weight: 30
      - name: Publicaciones
        url: publication
        weight: 40
      - name: Contacto
        url: contact
        weight: 50

ca:
  languageCode: ca
    #  contentDir: content/ca
  menus:
    main:
      - name: Recerca
        url: research
        weight: 10
      - name: Equipo
        url: people
        weight: 20
      - name: Notícies
        url: post
        weight: 30
      - name: Publicacions
        url: publication
        weight: 40
      - name: Contacte
        url: contact
        weight: 50
